config/routes.rb
Rails.application.routes.draw do

  root 'rooms#index'

  resources :rooms, only: [:index] do
    collection do
      post :find
    end
    resources :events, only: [:create]
  end

end

app/models/event.rb
class Event
  CURRENT = 5.minutes

  def self.all_of_today(room)
    all_between(room, Time.current, Time.current.end_of_day)
  end

  def self.all_between(room, from_time, to_time)
    events     = []
    page_token = nil

    begin
      result = Api.execute(list_query(room, from_time, to_time, page_token))
      events += result.data.items
    end while page_token = result.data.next_page_token

    events.map{|event| new(event)}
  end

  def self.create(room, from_time, to_time, summary)
    result = Api.execute(create_query(room, from_time, to_time, summary))
    new(result.data)
  end

  def self.list_query(room, from_time, to_time, page_token=nil)
    {
      api_method: Api.calendar_api.events.list,
      parameters: {
        calendarId: room.id,
        maxResults: 100,
        singleEvents: true,
        orderBy: 'startTime',
        timeMin: from_time.utc.iso8601,
        timeMax: to_time.utc.iso8601
      }
    }.merge(page_token.nil? ? {} : {pageToken: page_token})
  end

  def self.create_query(room, from_time, to_time, summary)
    {
      api_method: Api.calendar_api.events.insert,
      parameters: { calendarId: 'primary' },
      headers: {'Content-Type' => 'application/json'},
      body: {
        summary: summary,
        location: room.name,
        attendees: [{ email: room.id }],
        start: { dateTime: from_time.utc.iso8601 },
        end: { dateTime: to_time.utc.iso8601 },
      }.to_json,
    }
  end

  private_class_method :list_query, :create_query


  def initialize(event)
    @raw_event_hash = event.to_hash
  end

  %w[status location creator attendees summary description].each do |method|
    define_method(method) do
      @raw_event_hash[method]
    end
  end

  def start_time
    Time.zone.parse(@raw_event_hash['start'].values.first)
  end

  def end_time
    Time.zone.parse(@raw_event_hash['end'].values.first)
  end

  def current?
    Time.current >= start_time - CURRENT && Time.current < end_time
  end

  def inspect
    "#<Event: #location='#{location}' #summary='#{summary}' #status='#{status}' #start_time='#{start_time}' #end_time='#{end_time}>"
  end
end

app/models/room.rb
require 'yaml'

class Room
  ALL = YAML.load_file(File.join(File.dirname(__FILE__), '..', '..', 'config', 'meeting_rooms.yml'))

  def self.all
    @all ||= begin
      ALL.map do |id, attrs|
        new(id, attrs)
      end
    end
  end

  def self.find_by_name(name)
    all.detect { |room| room.name == name.downcase.to_s }
  end

  def self.find_by_id(id)
    all.detect { |room| room.id == id }
  end

  def self.all_free_now?
    Api::FreeBusy.is_free_now?(all)
  end

  def self.current_free_rooms
    Api::FreeBusy.is_free_now?(all).select { |_, free| free }.keys
  end

  attr_reader :id

  def initialize(id, attrs)
    @id    = id
    @attrs = attrs
  end

  def name
    @attrs['name']
  end

  def has_projector?
    @attrs['projector']
  end

  def max_occupants
    @attrs['max_occupants']
  end

  def is_free_now?
    result = Api::FreeBusy.is_free_now?(self)
    result.detect{|room, _| self.id == room.id}.last
  end

  def is_free_between?(from_time, to_time)
    result = Api::FreeBusy.is_free_between?(self, from_time, to_time)
    result.detect{|room, _| self.id == room.id}.last
  end

  def inspect
    "#<Room: #name='#{name}' #id='#{id}'>"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def create
    @room = Room.find_by_name(params[:room_id])
    if params[:plan] == 'adhoc'
      duration  = params[:duration].to_i
      @from_time = Time.current
      @to_time   = @from_time + duration
    else
      @from_time = Time.zone.parse(params[:from_time])
      @to_time   = Time.zone.parse(params[:to_time])
    end

    event = Event.create(@room, @from_time, @to_time, 'Adhoc meeting')
    flash[:notice] = "We have booked '#{@room.name.humanize}' for you until #{event.end_time.to_formatted_s(:short)}"
    redirect_to rooms_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	  @rooms = Room.is_free_now?
	  		
	end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all_free_now?
  end

  def find
    projector_required = params[:projector].present?
    @rooms = AvailableRoomService.find_next_available_room_for(params[:date].to_date, params[:duration].to_i, projector_required)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

	def call_status_class(room_free)
		if room_free
			'free'
		else
			'busy'
		end
	end

	def call_square(room_free)
		if room_free
			'free_square'
		else
			'busy_square'
		end
	end

	def call_td(room_free)
		if room_free
			'free_td'
		else
			'busy_td'
		end
	end

	def current_event(room)
		event = Event.all_of_today(room).detect do |event|
					event.current?
				end
		return  if event.nil?

		if !event.summary.present?

			event.creator['email']
		else
			event.summary
				
		end
	end

	def current_event_end_time(room)
		event = Event.all_of_today(room).detect do |event|
					event.current?
				end
		return  if event.nil?


	  event.end_time.strftime('%H:%M')
				
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper

  def find_room(name)
    @rooms.detect { |room, _| room.name == name.to_s.downcase }
  end

  def call_td(room_free)
    if room_free
      'free_td'
    else
      'busy_td'
    end
  end

  def current_event_summary(room)
    event = current_event(room)

    if event.nil?
      'Cannot find event'
    elsif event.summary.present?
      event.summary
    elsif event.description.present?
      event.description
    else
      event.creator['email']
    end
  end

  def current_event_end_time(room)
    event = current_event(room)
    return 'Cannot find event' if event.nil?

    end_time = event.end_time

    if end_time > Time.zone.local(Time.current.year, Time.current.month, Time.current.day, 17)
      'end of the day'
    else
      l(event.end_time, format: :time_only)
    end
  end

  def find_room_dates_array(number_of_entries)
    array = []
    date  = Date.today

    number_of_entries.times.each do
      while date.saturday? || date.sunday?
        date = date.tomorrow
      end
      array += [[find_room_dates_display_value(date) , date]]
      date = date.tomorrow
    end

    array
  end

  def find_room_duration_array
    [
      ['30 minutes', 30.minutes],
      ['1 hour',     1.hour],
      ['2 hours',    2.hour],
    ]
  end


  private

  def current_event(room)
    event = Event.all_of_today(room).detect { |event| event.current? }
  end

  def find_room_dates_display_value(date)
    if date.today?
      'Today'
    elsif date == Date.tomorrow
      'Tomorrow'
    else
      date.strftime('%A')
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meetopia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

<%= yield %>

</body>
</html>

app/views/rooms/find.haml
- if @rooms.empty?
  %h1 Sorry, no meeting rooms found for your search.
- else
  %h1 Here is what we have found based on your search:
  %table{:class => "find"}
    - @rooms.each do |room, time_hash|
      %tr
        %td= room.name.humanize
        %td= "From: #{l(time_hash[:start])}"
        %td= "To: #{l(time_hash[:end])}"
        %td= link_to 'Book it', room_events_path(room.name, duration: 1.hour, from_time: time_hash[:start], to_time: time_hash[:end]), :method=> :post

app/views/rooms/index.haml
.container.floor-plan
.row
  .col-md-12.col-xs-12.col-sm-12.col-md-12.col-lg-12 Reception area
.row
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6= render partial: 'rooms/partials/room_cell', locals: {name: :customer_experience_1}
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6= render partial: 'rooms/partials/room_cell', locals: {name: :customer_experience_2}
.row
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6= render partial: 'rooms/partials/room_cell', locals: {name: :kingston}
.row
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6= render partial: 'rooms/partials/room_cell', locals: {name: :elbistan}
.row
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6= render partial: 'rooms/partials/room_cell', locals: {name: :grimsby}
.row
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6
  .col-md-6.col-xs-6.col-sm-6.col-md-6.col-lg-6= render partial: 'rooms/partials/room_cell', locals: {name: :test_room}



/ <table class='floor_plan'>


/   <tr>
/     <%= render partial: 'rooms/partials/room_cell', locals: {name: :customer_experience_1} %>

/     <%= render partial: 'rooms/partials/room_cell', locals: {name: :customer_experience_2} %>


/     <td></td>
/     <td></td>
/     <td> Sarah G's seat</td>
/   </tr>




/   <tr>
/     <td class='tall', colspan=2></td>
/     <%= render partial: 'rooms/partials/room_cell', locals: {name: :kingston} %>
/   </tr>


/   <tr>
/     <td class='tall', colspan=2></td>
/     <%= render partial: 'rooms/partials/room_cell', locals: {name: :elbistan} %>
/   </tr>

/   <tr>
/     <td class='tall', colspan=2></td>
/     <%= render partial: 'rooms/partials/room_cell', locals: {name: :grimsby} %>
/   </tr>


/ </table>

/ <table>
/   <tr>
/     <%= render partial: 'rooms/partials/room_cell', locals: {name: :test_room} %>
/   </tr>
/   <tr>
/     <td>
/       Meetopia<br>
/       V 0.1
/     </td>
/   </tr>
/ </table>


%p
  find me a room:
  = form_tag(find_rooms_path, method: :post) do
    = select_tag "date", options_for_select(find_room_dates_array(5))
    = select_tag "duration", options_for_select(find_room_duration_array)
    = submit_tag 'find'

app/views/rooms/index.html.erb
<table>
  <tr>
    <%= render partial: 'rooms/partials/room_cell', locals: {name: :customer_experience_1} %>

    <%= render partial: 'rooms/partials/room_cell', locals: {name: :customer_experience_2} %>

    <td>
      <h1 align="center">Meetopia</h1>
      <i>"The Meeting Room Tool"</i>
    </td>
  </tr>

  <tr>
    <%= render partial: 'rooms/partials/room_cell2', locals: {name: :kingston} %>
    <td class='tall', colspan=1>
    Find me a room:<br>
    <%= form_tag(find_rooms_path, method: :post) do -%>
    <%= select_tag "date", options_for_select(find_room_dates_array(5)) %>
    <%= select_tag "duration", options_for_select(find_room_duration_array) %>
    <%= label_tag do %>
      <%= check_box_tag :projector %>
      projector?
    <% end %>
    <%= submit_tag 'find' %>
  <% end -%>

    </td>

  </tr>


  <tr>
    <%= render partial: 'rooms/partials/room_cell2', locals: {name: :elbistan} %>
    <td class='tall', colspan=1></td>
  </tr>

  <tr>
    <%= render partial: 'rooms/partials/room_cell2', locals: {name: :grimsby} %>
    <td class='tall', colspan=1>
    Rooms are layed out in the same way they look in the floorplan.
    </td>
  </tr>
  <tr>
    <td colspan=2></td>
    <%= render partial: 'rooms/partials/room_cell', locals: {name: :test_room} %>
  </tr>
</table>

app/views/rooms/partials/_room_cell.haml
- room, room_is_free = find_room(name)

%td{class: call_td(room_is_free)}
  %h3= room.name.to_s.humanize
  - unless room_is_free
    %p{style: 'font-size: 10px'}= current_event_summary(room)
    = "Busy until #{current_event_end_time(room)}"
  - else
    %p Free
    %p
      Book for the next:
      = link_to '30 mins', room_events_path(room.name, duration: 30.minutes, plan: 'adhoc'), :method=> :post
      |
      = link_to '1 hour', room_events_path(room.name, duration: 1.hour, plan: 'adhoc'), :method=> :post

app/views/rooms/partials/_room_cell2.html.erb
<% room, room_is_free = find_room(name) %>

<td colspan=2, class='<%= call_td(room_is_free) %>'>
  <h3><strong><%= room.name.to_s.humanize %></strong></h3><br>
  <% unless room_is_free %>
    Busy until <%= current_event_end_time(room) %><br>
  <%= current_event_summary(room) %>
  <% else %>
    Free<br>
    Book for the next:
    <%= link_to '30 mins', room_events_path(room.name, duration: 30.minutes, plan: 'adhoc'), :method=> :post %>
    |
    <%= link_to '1 hour', room_events_path(room.name, duration: 1.hour, plan: 'adhoc'), :method=> :post %>
  <% end %>
</td>